"""Shared Google OAuth2 authentication for Gmail and Contacts.

Loads user-level OAuth2 credentials from a saved token file
(generated by scripts/google_oauth.py) and builds API service clients.
"""

import json
import logging

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from skippy.config import settings

logger = logging.getLogger("skippy")

_credentials = None


def _get_credentials() -> Credentials:
    """Load and cache OAuth2 credentials, refreshing if expired."""
    global _credentials
    if _credentials and _credentials.valid:
        return _credentials

    if _credentials and _credentials.expired and _credentials.refresh_token:
        _credentials.refresh(Request())
        # Save refreshed token back to disk
        _save_token(_credentials)
        return _credentials

    with open(settings.google_oauth_token_json) as f:
        token_data = json.load(f)

    _credentials = Credentials(
        token=token_data.get("token"),
        refresh_token=token_data.get("refresh_token"),
        token_uri=token_data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=token_data.get("client_id"),
        client_secret=token_data.get("client_secret"),
        scopes=token_data.get("scopes"),
    )

    if _credentials.expired and _credentials.refresh_token:
        _credentials.refresh(Request())
        _save_token(_credentials)

    return _credentials


def _save_token(creds: Credentials) -> None:
    """Persist refreshed credentials back to the token file."""
    try:
        token_data = {
            "token": creds.token,
            "refresh_token": creds.refresh_token,
            "token_uri": creds.token_uri,
            "client_id": creds.client_id,
            "client_secret": creds.client_secret,
            "scopes": list(creds.scopes) if creds.scopes else [],
        }
        with open(settings.google_oauth_token_json, "w") as f:
            json.dump(token_data, f, indent=2)
    except Exception:
        logger.warning("Could not save refreshed token to disk", exc_info=True)


# Cached service instances
_services: dict[str, object] = {}


def get_google_user_service(api: str, version: str):
    """Build and cache a Google API service using OAuth2 user credentials.

    Args:
        api: The API name (e.g., 'gmail', 'people').
        version: The API version (e.g., 'v1').

    Returns:
        A googleapiclient service object.
    """
    cache_key = f"{api}:{version}"
    if cache_key in _services:
        # Ensure credentials are still valid
        _get_credentials()
        return _services[cache_key]

    creds = _get_credentials()
    service = build(api, version, credentials=creds)
    _services[cache_key] = service
    logger.info("Google %s %s service initialized", api, version)
    return service
